import { describe, expect, it } from "vitest";

import { CodexInternalProvider } from "../src/providers/codex-internal";
import { inferSuggestionFromUrl } from "../src/url-intake";

describe("inferSuggestionFromUrl", () => {
  it("parses npm links", () => {
    const suggestion = inferSuggestionFromUrl("https://www.npmjs.com/package/@acme/mcp-filesystem");

    expect(suggestion.sourceKind).toBe("npm");
    expect(suggestion.suggestedName).toBe("mcp-filesystem");
    expect(suggestion.suggestedCommand).toBe("npx");
    expect(suggestion.provider).toBe("heuristic-fallback");
  });
});

describe("CodexInternalProvider", () => {
  it("returns fallback when no API key is provided", async () => {
    const provider = new CodexInternalProvider({
      apiKey: undefined,
      fetchImpl: async () => ({
        ok: true,
        status: 200,
        text: async () => "<html><body>Sample docs</body></html>"
      })
    });

    const suggestion = await provider.suggestFromUrl("https://github.com/acme/mcp-server");

    expect(suggestion.mode).toBe("fallback");
    expect(suggestion.provider).toBe("heuristic-fallback");
  });

  it("throws in strict mode when docs cannot be fetched for URL input", async () => {
    const provider = new CodexInternalProvider({
      strictMode: true,
      apiKey: "test-key",
      fetchImpl: async () => ({
        ok: false,
        status: 404,
        text: async () => "not found"
      })
    });

    await expect(
      provider.suggestFromUrl("https://example.com/mcp-docs")
    ).rejects.toThrow("Strict analysis is enabled");
  });

  it("uses Codex Internal response when JSON output is valid", async () => {
    const provider = new CodexInternalProvider({
      apiKey: "test-key",
      fetchImpl: async () => {
        return {
          ok: true,
          status: 200,
          text: async () =>
            JSON.stringify({
              output_text: JSON.stringify({
                sourceKind: "github",
                suggestedName: "server",
                suggestedCommand: "npx",
                suggestedArgs: ["-y", "acme/server"],
                summary: "Generated by Codex Internal.",
                questions: [
                  {
                    id: "scope",
                    text: "All platforms or selected platforms?"
                  }
                ]
              })
            })
        };
      }
    });

    const suggestion = await provider.suggestFromUrl("https://github.com/acme/server");

    expect(suggestion.mode).toBe("live");
    expect(suggestion.provider).toBe("codex-internal");
    expect(suggestion.suggestedName).toBe("server");
    expect(suggestion.questions).toHaveLength(1);
  });
});
